parameters:
    tenolo_doctrine_table_prefix.event.table_prefix.class: Tenolo\Bundle\DoctrineTablePrefixBundle\EventListener\TablePrefixListener
    doctrine.orm.listeners.resolve_target_entity.class: Tenolo\Bundle\DoctrineTablePrefixBundle\EventListener\ResolveTargetEntityListener

services:
    tenolo_doctrine_table_prefix.event.table_prefix:
        class: %tenolo_doctrine_table_prefix.event.table_prefix.class%
<<<<<<< HEAD
        arguments: ["@service_container", "%database_prefix%"]
=======
        arguments: [@service_container, %database_prefix%]
>>>>>>> 1.1
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata,  method: loadClassMetadata, priority: -10 }
